# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: BuildInstaller@1
  inputs:
    installTaskMode: 'solution'
    SlnPath: 'VS2015-WPF-APP.sln'
    VsVersion: 'VS2015'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Rename-Item $(Build.ArtifactStagingDirectory)/Setup1.msi Setup1-1.0.$(Build.BuildId).0.msi

- task: S3Upload@1
  inputs:
    awsCredentials: 'My AWS connection'
    regionName: 'us-east-1'
    bucketName: 'msi-app'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '**'
    targetFolder: 'myapp'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '7d3f8166-469c-4e60-8c66-20ffd4910644/0f18236b-78b0-47a5-b044-610ff1b410c8'
    vstsFeedPackagePublish: 'MyAPP-1.0'
    versionOption: 'patch'